### ISSUE TITLE
Remove rule to error on unassigned expresions

### ISSUE THREAD

**Issue by hectorhuertas** [repositive/typescript#3]

**Comment by Istar-Eldritch** [comment]
@hectorhuertas can you describe a bit more this issue? I don't really get what this is about

**Comment by hectorhuertas** [comment]
The linter complains if a function is called without assigning its value somewhere. The rps index file has a great example of the boilerplate needed to go around that type of error. I think its better to dont have that rule in the linter than to use boilerplate.

**Comment by Istar-Eldritch** [comment]
Oh, you are talking about the `assign but not used variable` thing?

**Comment by hectorhuertas** [comment]
`unused expression, expected an assignment or functiontion call (no-unused-expression)`

**Comment by hectorhuertas** [comment]
maybe the rps index has a bug that we haven't realized and the linter is letting us know about it? I have only seen this error there

**Comment by hectorhuertas** [comment]
Closing as this is not a priority and seems abandoned
